name: Heroku-Cron
on:
  schedule: [{cron: "0 8 * * *"}]
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "eller-time-bot"
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            justlogin: true
      - run: "heroku ps:scale worker=1 --app eller-time-bot"
