name: Heroku-Stop
on:
  schedule: [{cron: "0 20 * * *"}]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - run: "heroku login -i"
      - run: "{{secrets.HEROKU_EMAIL}}"
      - run: "{{secrets.HEROKU_PASSWORD}}"
      - run: "heroku ps:scale worker=0 --app eller-time-bot"
