name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Heroku
        env:
          TOKEN: ${{ secrets.HEROKU_TOKEN }}
          APP: eller-time-bot
        run: |
          git remote add heroku https://heroku:$TOKEN@git.heroku.com/$APP.git
          git push heroku HEAD:master -f