name: Heroku-Cron
on:
  schedule: [{cron: "0 8 * * *"}]
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  open-worker:
    runs-on: ubuntu-latest
    steps:
      - name: apply
        run: HEROKU_API_KEY='82a6c19a-ed35-4ced-b029-bae9559995a9' heroku ps:scale worker=1 -a eller-time-bot
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_TOKEN}}

        
