name: Heroku-Cron
on:
  schedule: [{cron: "0 8 * * *"}]
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - run: "heroku login -i"
      - run: "{{secrets.HEROKU_EMAIL}}"
      - run: "{{secrets.HEROKU_PASSWORD}}"
      - run: "heroku ps:scale worker=1 --app eller-time-bot"
