name: Heroku-Stop
on:
  schedule: [{cron: "0 20 * * *"}]

jobs:
  close-worker:
    runs-on: ubuntu-latest
    steps:
      - name: apply
        run: heroku ps:scale worker=0 -a eller-time-bot
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_TOKEN}}
