name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add heroku remote
        run : "git remote add heroku https://git.heroku.com/eller-time-bot.git" 
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "eller-time-bot" #Must be unique in Heroku
          heroku_email: "io.yuange86@gmail.com"