name: Heroku-Cron
on:
  schedule: [{cron: "0 8 * * *"}]
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  open-worker:
    runs-on: ubuntu-latest
    steps:
      # - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "eller-time-bot"
      #     heroku_email: ${{secrets.HEROKU_EMAIL}}
      #     justlogin: true
      # - run: heroku ps:scale worker=0 -a eller-time-bot
      # - run: |
      #     cat > ~/.netrc
      #       machine api.heroku.com
      #         login io.yuange86@gmail.com
      #         password $TOKEN
      #       machine git.heroku.com
      #         login io.yuange86@gmail.com
      #         password $TOKEN
      #     EOF
      # - run: heroku ps:scale worker=0 -a eller-time-bot
      #   env:
      #     TOKEN: ${{secrets.HEROKU_API_TOKEN}}
      - name: create
        run: heroku authorizations:create
      - name: apply
        run: HEROKU_API_KEY='$HEROKU_API_TOKEN' heroku whoami
        env:
          TOKEN: ${{secrets.HEROKU_API_TOKEN}}

        
