name: Heroku-Cron
on:
  schedule: 
    - cron: "0 23 * * *" # timezone: Asia/Seoul  --  UTF +9:00
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  open-worker:
    runs-on: ubuntu-latest
    steps:
      - name: apply
        run: heroku ps:scale worker=1 -a eller-time-bot
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_TOKEN}}

        
